name: "Workflow Exemplo"
on:
  workflow_dispatch:

jobs:
  configurar:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer o checkout do código
        uses: actions/checkout@v4 #essa é uma action que permite ter acesso ao código durante a exedução do job
        with:
          ref: main # ref é um input que di qual será o nome da branch que utlizaremos
      - name: "Configurar o git na pipeline"
        run: |
              echo "Configurando o git na pipeline"
              echo "Configurando o git com sucesso"
      - name: "Configurando o user no git"
        run: |
          echo "Configurando o git user.name" 
  construir:
    runs-on: ubuntu-24.04
    needs:
      - configurar
    steps:
      - name: "Instalar as dependencias"
        run: echo 'Instalando as dependencias'               